site_name: Teknofest Simulator
site_url: https://harunkurtdev.github.io/teknofest-simulator
site_description: Teknofest Simulator
site_author: Harun KURT

nav:
  - Home: index.md
  - Installation:
      - Requirements: installation/requirements.md
      - Setup: installation/setup.md
  - Tarimsal İnsansiz Araçlar:
      - Tarimsal İnsansiz Araci Görevi: tika/tika.md
      - Tarimsal İnsansiz Araci Görev Çözümü: tika/tika-apply.md
  - İnsansiz Deniz Araci Yarişmasi:
      - İnsansiz Deniz Araci Yarişmasi Görevi: ida/ida.md
      - İnsansiz Deniz Araci Yarişmasi Görev Çözümü: ida/ida-apply.md
  - İnsansiz Kara Araci Yarişmasi:
      - İnsansiz Kara Araci Yarişmasi Görevi: ika/ika.md
      - İnsansiz Kara Araci Yarişmasi Görev Çözümü: ika/ika-apply.md
  # - Usage:
  #     - Connecting Webots and Simulink: usage/connecting.md
  #     - Running Simulations: usage/running.md
  #     - Customizing the Bridge: usage/customization.md
  #     # - Data Exchange: usage/data_exchange.md
  # - Advanced:
  #     - Debugging: advanced/debugging.md
  #     - Export ROS2 Package: advanced/export-ros2.md
  # - Examples:
  #     - Inverted Pendulum Example: examples/inverted-pendulum.md
  #     - Rotary Inverted Pendulum Example: examples/rotary-inverted-pendulum.md
  #     - Wheel Chair Example: examples/wheel-chair.md
  #     - Crazyflie Drone Example: examples/crazyflie-drone.md
  #     - BlueBoat USV Example: examples/blueboat-usv.md
  # - Troubleshooting: troubleshooting.md
  # - FAQ: faq.md
  # - References: references.md

theme:
  name: material
  font:
    text: Merriweather Sans
    code: Red Hat Mono
  logo: assets/images/logo.png
  favicon: assets/images/favicon.ico
  features:
    - navigation.footer
  palette:
    # Dark Mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Dark mode
      primary: green
      accent: deep purple

    # Light Mode
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Light mode
      primary: blue
      accent: deep orange

markdown_extensions:
  - attr_list
  - def_list
  - fenced_code
  - footnotes
  - tables
  - toc:
      permalink: true
      permalink_class: headerlink
      permalink_title: Permalink
  - pymdownx.betterem
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - pymdownx.details
  - pymdownx.magiclink
  - pymdownx.tasklist

extra:
  social:
    - icon: simple/youtube
      link: https://youtube.com/@harunkurtdev
    # - icon: simple/linkedin
      # link: https://linkedin.com/in/

copyright: Copyright &copy; 2025 harunkurtdev